# Generated by Django 5.0.6 on 2024-06-16 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_cost',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Class cost'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Last name'),
        ),
    ]
