# Generated by Django 5.0.6 on 2024-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_lesson_amount_alter_lesson_date_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
